USE [master]
 GO
 
 /****** Object:  Database [QLSV]    Script Date: 3/25/2025 3:02:12 PM ******/
 CREATE DATABASE [QLSV]
  CONTAINMENT = NONE
  ON  PRIMARY 
 ( NAME = N'QLSV', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLDEV20022004\MSSQL\DATA\QLSV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
  LOG ON 
 ( NAME = N'QLSV_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLDEV20022004\MSSQL\DATA\QLSV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
  WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
 GO
 
 /*****T?O B?NG SINHVIEN*/
 
 CREATE TABLE [dbo].[Sinhvien](
 	[maSV] [nvarchar](20) NOT NULL,
 	[hoten] [nvarchar](20) NULL,
 	[ngaysinh] [date] NULL,
  CONSTRAINT [PK_Sinhvien] PRIMARY KEY CLUSTERED 
 (
 	[maSV] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 /**T?O B?NG LOP*/
 CREATE TABLE [dbo].[Lop](
 	[malop] [nchar](10) NOT NULL,
 	[tenlop] [nvarchar](10) NULL,
  CONSTRAINT [PK_Lop] PRIMARY KEY CLUSTERED 
 (
 	[malop] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 /**T?O B?NG GVCN*/
 CREATE TABLE [dbo].[GVCN](
 	[malop] [nchar](10) NOT NULL,
 	[magv] [nvarchar](20) NOT NULL,
 	[HK] [nvarchar](20) NOT NULL,
  CONSTRAINT [PK_GVCN] PRIMARY KEY CLUSTERED 
 (
 	[malop] ASC,
 	[magv] ASC,
 	[HK] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK_GVCN_GiaoVien] FOREIGN KEY([magv])
 REFERENCES [dbo].[GiaoVien] ([magv])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK_GVCN_GiaoVien]
 GO
 
 ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK_GVCN_Lop1] FOREIGN KEY([malop])
 REFERENCES [dbo].[Lop] ([malop])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK_GVCN_Lop1]
 GO
 /**T?O B?NG LOPSV*/
 CREATE TABLE [dbo].[LopSV](
 	[malop] [nchar](10) NOT NULL,
 	[masv] [nvarchar](20) NOT NULL,
 	[chucvu] [nvarchar](20) NULL,
  CONSTRAINT [PK_LopSV] PRIMARY KEY CLUSTERED 
 (
 	[malop] ASC,
 	[masv] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 ALTER TABLE [dbo].[LopSV]  WITH CHECK ADD  CONSTRAINT [FK_LopSV_Lop] FOREIGN KEY([malop])
 REFERENCES [dbo].[Lop] ([malop])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[LopSV] CHECK CONSTRAINT [FK_LopSV_Lop]
 GO
 
 ALTER TABLE [dbo].[LopSV]  WITH CHECK ADD  CONSTRAINT [FK_LopSV_Sinhvien] FOREIGN KEY([masv])
 REFERENCES [dbo].[Sinhvien] ([masv])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[LopSV] CHECK CONSTRAINT [FK_LopSV_Sinhvien]
 GO
 /**T?O B?NG GIAOVIEN*/
 CREATE TABLE [dbo].[GiaoVien](
 	[magv] [nvarchar](20) NOT NULL,
 	[hoten] [nvarchar](20) NULL,
 	[ngaysinh] [date] NULL,
 	[mabm] [nvarchar](20) NULL,
  CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED 
 (
 	[magv] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 ALTER TABLE [dbo].[GiaoVien]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVien_BoMon] FOREIGN KEY([mabm])
 REFERENCES [dbo].[BoMon] ([mabm])
 ON UPDATE CASCADE
 GO
 /**T?O B?NG BOMON*/
 CREATE TABLE [dbo].[BoMon](
 	[mabm] [nvarchar](20) NOT NULL,
 	[tenbm] [nvarchar](20) NULL,
 	[makhoa] [nvarchar](20) NULL,
  CONSTRAINT [PK_BoMon] PRIMARY KEY CLUSTERED 
 (
 	[mabm] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 ALTER TABLE [dbo].[BoMon]  WITH CHECK ADD  CONSTRAINT [FK_BoMon_Khoa] FOREIGN KEY([makhoa])
 REFERENCES [dbo].[Khoa] ([makhoa])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[BoMon] CHECK CONSTRAINT [FK_BoMon_Khoa]
 GO
 /**T?O B?NG KHOA*/
 CREATE TABLE [dbo].[Khoa](
 	[makhoa] [nvarchar](20) NOT NULL,
 	[tenkhoa] [nvarchar](20) NULL,
  CONSTRAINT [PK_Khoa] PRIMARY KEY CLUSTERED 
 (
 	[makhoa] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 /**T?O B?NG MONHOC*/
 CREATE TABLE [dbo].[MonHoc](
 	[mamon] [nvarchar](20) NOT NULL,
 	[tenmon] [nvarchar](20) NULL,
 	[stc] [int] NULL,
  CONSTRAINT [PK_MonHoc] PRIMARY KEY CLUSTERED 
 (
 	[mamon] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 /**T?O B?NG LOPHP*/
 CREATE TABLE [dbo].[LopHP](
 	[malophp] [nvarchar](20) NOT NULL,
 	[tenlophp] [nvarchar](20) NULL,
 	[HK] [nvarchar](20) NULL,
 	[mamon] [nvarchar](20) NULL,
 	[magv] [nvarchar](20) NULL,
  CONSTRAINT [PK_LopHP] PRIMARY KEY CLUSTERED 
 (
 	[malophp] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_GiaoVien] FOREIGN KEY([magv])
 REFERENCES [dbo].[GiaoVien] ([magv])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_GiaoVien]
 GO
 
 ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_MonHoc] FOREIGN KEY([mamon])
 REFERENCES [dbo].[MonHoc] ([mamon])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_MonHoc]
 GO
 /**T?O B?NG DKMH*/
 
 CREATE TABLE [dbo].[DKMH](
 	[malophp] [nvarchar](20) NOT NULL,
 	[masv] [nvarchar](20) NOT NULL,
 	[diemtp] [float] NULL,
 	[diemthi] [float] NULL,
 	[phanchamthi] [float] NULL,
  CONSTRAINT [PK_DKMH] PRIMARY KEY CLUSTERED 
 (
 	[malophp] ASC,
 	[masv] ASC
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
 ) ON [PRIMARY]
 GO
 
 ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [FK_DKMH_LopHP] FOREIGN KEY([malophp])
 REFERENCES [dbo].[LopHP] ([malophp])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [FK_DKMH_LopHP]
 GO
 
 ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [FK_DKMH_Sinhvien] FOREIGN KEY([masv])
 REFERENCES [dbo].[Sinhvien] ([masv])
 ON UPDATE CASCADE
 GO
 
 ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [FK_DKMH_Sinhvien]
 GO